root = "."
tmp_dir = "/tmp/air"

[build]
cmd = "GOCACHE=/tmp/go-build-cache XDG_CACHE_HOME=/tmp/.cache go build -o /tmp/air/app ."
bin = "/tmp/air/app"
full_bin = "/tmp/air/app api"
include_ext = ["go", "tpl", "tmpl", "yaml", "yml", "json", "env", "toml", "mod", "sum"]
exclude_dir = ["tmp", "vendor", ".git"]
exclude_file = []
include_dir = []
exclude_unchanged = true
follow_symlink = false
log = "/tmp/air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true