services:
  db:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=core
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d core -U core" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  db:
    driver: local
