services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: core
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/migrations
    networks:
      - local-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d core -U core" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel notice
    volumes:
      - redis-data:/data
    networks:
      - local-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  core:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - local-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  local-network:
    driver: bridge