version: '3.8'

services:
  database:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: 'core'
      MYSQL_USER: 'matchally'
      MYSQL_PASSWORD: 'secret'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - 3307:3306

  core:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  database:
    driver: local