services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - /var/lib/redis:/data
    command: redis-server --appendonly yes

  core:
    build:
      target: prod
    environment:
      - GO_ENV=prod
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s