version: '3.8'

services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: 'core'
      MYSQL_USER: 'matchally'
      MYSQL_PASSWORD: 'secret'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - 3306:3306
    healthcheck:
            test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
            timeout: 5s
            interval: 5s
            retries: 10

  core:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  db:
    driver: local