services:
  db:
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  core:
    build:
      target: dev
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    environment:
      - GO_ENV=dev
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true

volumes:
  go-modules: