INSERT INTO users (name, email, password)
VALUES
("Alice", "alice@example.com","password"),
("Bob", "bob@example.com","password"),
("Charlie", "charlie@example.com","password"),
("David", "david@example.com","password"),
("Eve", "eve@example.com","password"),
("Fiona", "fiona@example.com","password"),
("Grace", "grace@example.com","password"),
("Heidi", "heidi@example.com","password"),
("Ivan", "ivan@example.com","password"),
("Judy", "judy@example.com","password"),
("Karl", "karl@example.com","password"),
("Liam", "liam@example.com","password"),
("Mona", "mona@example.com","password"),
("Nina", "nina@example.com","password"),
("Omar", "omar@example.com","password"),
("Pete", "pete@example.com","password"),
("Quin", "quin@example.com","password"),
("Ruth", "ruth@example.com","password"),
("Sara", "sara@example.com","password"),
("Tina", "tina@example.com","password"),
("Ulla", "ulla@example.com","password"),
("Vera", "vera@example.com","password"),
("Wendy", "wendy@example.com","password"),
("Xena", "xena@example.com","password"),
("Yara", "yara@example.com","password"),
("Zara", "zara@example.com","password");