openapi: "3.0.2"

info:
  title: Core
  version: 1.0.0
  description: Endpoints for interacting with Core
  contact:
    name: Sebastian Holmgaard
    url: https://github.com/MatchAlly/core
    email: sebholmgaard@gmail.com

servers:
  - url: https://api-matchally.koyeb.app/
  - url: "{scheme}://{host}{base}"
    description: Custom
    variables:
      scheme:
        default: "http"
        enum:
          - "http"
          - "https"
      host:
        default: "localhost:8080"
      base:
        default: ""

tags:
  - name: Authorization endpoints
    description: "Endpoints relating to authorization"
  - name: User endpoints
    description: "Endpoints relating to users"
  - name: Club endpoints
    description: "Endpoints relating to Clubs"

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Bearer token from MatchAlly"

paths:
  # Authorization endpoints
  auth/signup:
    post:
      operationId: Signup
      tags:
        - Authorization endpoints
      description: |
        Endpoint for users to signup to MatchAlly
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@matchally.com"
                name:
                  type: string
                  example: "John Doe"
                password:
                  type: string
                  example: "password1234"
      responses:
        "201":
          description: "Signup successful"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  auth/login:
    post:
      operationId: Login
      tags:
        - Authorization endpoints
      description: |
        Endpoint for users to login to MatchAlly
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@matchally.me"
                password:
                  type: string
                  example: "password1234"
      responses:
        "200":
          description: "Login successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  refreshToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  auth/refresh:
    post:
      operationId: Refresh
      tags:
        - Authorization endpoints
      description: |
        Endpoint for users refresh their access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      responses:
        "200":
          description: "Refresh successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  refreshToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  # User endpoints
  /user:
    delete:
      operationId: DeleteUser
      tags:
        - User endpoints
      security:
        - JWT: []
      description: |
        Endpoint for deleting a user.
        Only the user themselves can delete their account.
      responses:
        "200":
          description: "User deleted"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  /user/invites:
    get:
      operationId: GetInvites
      tags:
        - User endpoints
      security:
        - JWT: []
      description: |
        Endpoint for getting all invites for a user.
        Only the user themselves can get their invites.
      responses:
        "200":
          description: "Invites retrieved"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 123
                    clubId:
                      type: integer
                      example: 123
                    name:
                      type: string
                      example: "The Best Club"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  # Club endpoints
  /Club/users:
    get:
      operationId: GetUsersInClub
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for getting all users in an Club.
        Only users in the Club can get the users.
      responses:
        "200":
          description: "Users retrieved"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: "John Doe"
                    email:
                      type: string
                      example: "user@matchally.com"
                    role:
                      type: string
                      example: "admin"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  /club:
    put:
      operationId: UpdateClub
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for updating an Club.
        Only admins of the Club can update the Club.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "My Club"
      responses:
        "200":
          description: "Club updated"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"
    delete:
      operationId: DeleteClub
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for deleting an Club.
        Only admins of the Club can delete the Club.
      responses:
        "200":
          description: "Club deleted"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"
    post:
      operationId: CreateClub
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for creating an Club. The user creating the Club will be set as an admin.
        The session should be reauthenticated after creating an Club to get updated claims.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "My Club"
      responses:
        "201":
          description: "Club created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden, user is already in an Club"
        "500":
          description: "Internal Server Error"

  /Club/invites:
    post:
      operationId: InviteUserToClub
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for inviting a list of users to an Club.
        Only admins of the Club can invite users.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@matchally.com"
      responses:
        "201":
          description: "Users invited"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  /Club/users/{userId}:
    put:
      operationId: UpdateUserRole
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for updating a user's role in an Club.
        Only admins of the Club can update roles.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  example: "admin"
      responses:
        "200":
          description: "User role updated"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"
    delete:
      operationId: RemoveUserFromClub
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for removing a user from an Club.
        Only admins of the Club can remove users.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "User removed"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  /Club/users/virtual:
    post:
      operationId: AddVirtualUserToClub
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for adding virtual users to an Club.
        Only admins of the Club add virtual users.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "John Doe"
      responses:
        "200":
          description: "Virtual user added"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  /Club/users/{userId}/virtual/{virtualUserId}:
    post:
      operationId: TransferVirtualUserToUser
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for transfering the rating & statistics of a virtual user to a real user.
        The real users old rating & statistics will be deleted.
        The virtual user will be deleted.
        Only admins of the Club add virtual users.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
        - in: path
          name: virtualUserId
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Virtual user transfered to real user"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  /Club/matches:
    post:
      operationId: CreateMatch
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for creating a match.
        Only users in the Club can create matches.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                teamA:
                  type: array
                  items:
                    type: integer
                teamB:
                  type: array
                  items:
                    type: integer
                scoresA:
                  type: array
                  items:
                    type: integer
                scoresB:
                  type: array
                  items:
                    type: integer
                rated:
                  type: boolean
                  example: true
      responses:
        "201":
          description: "Match created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"

  /Club/top/{topX}/measures/{leaderboardType}:
    get:
      operationId: GetTopX
      tags:
        - Club endpoints
      security:
        - JWT: []
      description: |
        Endpoint for getting the top X players in an Club according to some measure.
        Also called a leaderboard.
        Only users in the Club can get the top X players.
      parameters:
        - in: path
          name: topX
          required: true
          schema:
            type: integer
        - in: path
          name: leaderboardType
          required: true
          schema:
            type: string
            enum:
              - "wins"
              - "win-streak"
              - "loss-streak"
              - "win-loss-ratio"
              - "rating"
              - "matches-played"
      responses:
        "200":
          description: "Top X players retrieved"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "500":
          description: "Internal Server Error"
